# KRAMDOWN
markdown: kramdown

# TITLE
title: Ida Webdeveloper
url: "localhost" # Aqui voce pode inserir seu endereço de domínio principal. Caso seu site esteja em subpasta, informe o endereço da pasta na baseurl como no exemplo abaixo.
      # url: "www.siteexemplo.com" ou baseurl: "/siteexemplo/".
baseurl: ""
permalink: "./pages/:title"

# INFORMATIONS
author: Ezequiel Sousa
description: Portifolio Ida Webdeveloper
keywords: Website,Portifolio,Dev,Portifolio Desenvolvedor,Developer,Webdesign
generator_dev: Sublime Text
favicon: favicon.ico
image: michael-dam-mEZ3PoFGs_k-unsplash.jpg

# REDES SOCIAIS
username_github: ezequielsousa-devbr
username_twitter:

# PAGES
about_perfil: michael-dam-mEZ3PoFGs_k-unsplash.jpg
about_alt: About Perfil

# INDEX
hero_image: michael-dam-mEZ3PoFGs_k-unsplash.jpg
hero_alt: Ida Webdeveloper

# ANALYTICS
google_analytics:
google_tags:
smartlook_analytics:

# HEADER NAVBARS:
navbar_main: Home
navbar_about: About
navbar_serv: Services
navbar_port: Portfolio
navbar_contact: Contact
navbar_blog: blog

# EXCLUIR
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - .jekyll-cache/
  - docs/
