# KRAMDOWN
markdown: kramdown

# TITLE
title: Ida Webdeveloper
url: "/index/"
baseurl: ""
permalink: "/pages/:title"

# INFORMATIONS
author: Ezequiel Sousa
description: Portifolio Ida Webdeveloper
keywords: Website,Portifolio,Dev,Portifolio Desenvolvedor,Developer,Webdesign
generator_dev: Sublime Text
favicon: favicon.ico

# PAGES
about_perfil: michael-dam-mEZ3PoFGs_k-unsplash.jpg
about_alt: About Perfil

# INDEX
hero_image: michael-dam-mEZ3PoFGs_k-unsplash.jpg
hero_alt: Ida Webdeveloper

# ANALYTICS
google_analytics:
google_tags:

# HEADER NAVBARS:
navbar_main: Home
navbar_about: About
navbar_serv: Services
navbar_port: Portifolio
navbar_contact: Contact

# EXCLUIR
exclude:
  - Gemfile.lock
  - .jekyll-cache/
  - README.md
